-- BarangayTogether: Supabase schema + RLS
-- Run this in Supabase SQL Editor.

-- 1) Profiles
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role text not null default 'resident' check (role in ('resident','admin')),
  status text not null default 'active' check (status in ('active','disabled')),
  email text,
  full_name text,
  contact_number text,
  address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists profiles_status_idx on public.profiles(status);

-- Keep updated_at fresh
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

-- Create a profile row on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, contact_number, address)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    coalesce(new.raw_user_meta_data->>'contact_number', ''),
    coalesce(new.raw_user_meta_data->>'address', '')
  )
  on conflict (id) do update
    set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Admin helper (bypasses RLS safely)
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin' and p.status = 'active'
  );
$$;

-- Prevent residents from changing their own role/status
create or replace function public.protect_profile_privileged_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Allow privileged server-side contexts (SQL Editor / migrations) where there is no JWT.
  if auth.uid() is null then
    return new;
  end if;

  if (new.role is distinct from old.role) and (not public.is_admin()) then
    raise exception 'Only admins can change role';
  end if;

  if (new.status is distinct from old.status) and (not public.is_admin()) then
    raise exception 'Only admins can change status';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_profiles_protect on public.profiles;
create trigger trg_profiles_protect
before update on public.profiles
for each row execute function public.protect_profile_privileged_fields();

-- 2) Activities
create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  activity_date date not null,
  start_time time not null,
  end_time time,
  location text not null,
  volunteers_needed integer not null check (volunteers_needed >= 1),
  status text not null default 'open' check (status in ('open','closed','cancelled','done')),
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists activities_date_idx on public.activities(activity_date);
create index if not exists activities_status_idx on public.activities(status);

drop trigger if exists trg_activities_updated_at on public.activities;
create trigger trg_activities_updated_at
before update on public.activities
for each row execute function public.set_updated_at();

-- 3) Participants
create table if not exists public.activity_participants (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  status text not null default 'joined' check (status in ('joined','cancelled')),
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (activity_id, user_id)
);

create index if not exists activity_participants_activity_idx on public.activity_participants(activity_id);
create index if not exists activity_participants_user_idx on public.activity_participants(user_id);

drop trigger if exists trg_activity_participants_updated_at on public.activity_participants;
create trigger trg_activity_participants_updated_at
before update on public.activity_participants
for each row execute function public.set_updated_at();

-- 4) Public stats (safe to expose without volunteer identities)
create table if not exists public.activity_stats (
  activity_id bigint primary key references public.activities (id) on delete cascade,
  joined_count integer not null default 0,
  updated_at timestamptz not null default now()
);

create or replace function public.recalc_activity_stats(p_activity_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  select count(*) into v_count
  from public.activity_participants ap
  where ap.activity_id = p_activity_id and ap.status = 'joined';

  insert into public.activity_stats (activity_id, joined_count, updated_at)
  values (p_activity_id, v_count, now())
  on conflict (activity_id) do update
    set joined_count = excluded.joined_count,
        updated_at = excluded.updated_at;
end;
$$;

create or replace function public.trg_recalc_activity_stats()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.recalc_activity_stats(coalesce(new.activity_id, old.activity_id));
  return null;
end;
$$;

drop trigger if exists trg_participants_stats_ins on public.activity_participants;
create trigger trg_participants_stats_ins
after insert on public.activity_participants
for each row execute function public.trg_recalc_activity_stats();

drop trigger if exists trg_participants_stats_upd on public.activity_participants;
create trigger trg_participants_stats_upd
after update on public.activity_participants
for each row execute function public.trg_recalc_activity_stats();

drop trigger if exists trg_participants_stats_del on public.activity_participants;
create trigger trg_participants_stats_del
after delete on public.activity_participants
for each row execute function public.trg_recalc_activity_stats();

create or replace function public.trg_init_activity_stats()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.activity_stats (activity_id, joined_count)
  values (new.id, 0)
  on conflict (activity_id) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_activities_stats_init on public.activities;
create trigger trg_activities_stats_init
after insert on public.activities
for each row execute function public.trg_init_activity_stats();

-- A safe public view for listings
create or replace view public.activities_public as
select
  a.id,
  a.title,
  a.description,
  a.activity_date,
  a.start_time,
  a.end_time,
  a.location,
  a.volunteers_needed,
  a.status,
  a.created_by,
  a.created_at,
  a.updated_at,
  coalesce(s.joined_count, 0) as joined_count,
  greatest(a.volunteers_needed - coalesce(s.joined_count, 0), 0) as slots_left
from public.activities a
left join public.activity_stats s on s.activity_id = a.id;

-- 5) RPC for capacity-safe join/cancel
create or replace function public.join_activity(p_activity_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_needed integer;
  v_status text;
  v_joined integer;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select a.volunteers_needed, a.status into v_needed, v_status
  from public.activities a
  where a.id = p_activity_id;

  if not found then
    raise exception 'Activity not found';
  end if;

  if v_status <> 'open' then
    raise exception 'Activity is not open';
  end if;

  select coalesce(s.joined_count, 0) into v_joined
  from public.activity_stats s
  where s.activity_id = p_activity_id;

  if v_joined >= v_needed then
    raise exception 'Activity is full';
  end if;

  insert into public.activity_participants (activity_id, user_id, status)
  values (p_activity_id, auth.uid(), 'joined')
  on conflict (activity_id, user_id) do update
    set status = 'joined',
        updated_at = now();

  perform public.recalc_activity_stats(p_activity_id);
end;
$$;

create or replace function public.cancel_activity(p_activity_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  update public.activity_participants
  set status = 'cancelled',
      updated_at = now()
  where activity_id = p_activity_id and user_id = auth.uid();

  perform public.recalc_activity_stats(p_activity_id);
end;
$$;

-- 6) RLS
alter table public.profiles enable row level security;
alter table public.activities enable row level security;
alter table public.activity_participants enable row level security;
alter table public.activity_stats enable row level security;

-- profiles
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
for update to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

-- activities (publicly visible)
drop policy if exists "activities_select_public" on public.activities;
create policy "activities_select_public" on public.activities
for select to anon, authenticated
using (true);

drop policy if exists "activities_write_admin" on public.activities;
create policy "activities_write_admin" on public.activities
for insert to authenticated
with check (public.is_admin());

drop policy if exists "activities_update_admin" on public.activities;
create policy "activities_update_admin" on public.activities
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "activities_delete_admin" on public.activities;
create policy "activities_delete_admin" on public.activities
for delete to authenticated
using (public.is_admin());

-- activity_participants
drop policy if exists "participants_select" on public.activity_participants;
create policy "participants_select" on public.activity_participants
for select to authenticated
using (user_id = auth.uid() or public.is_admin());

-- Users join/cancel via RPC only (admin can still manage)
drop policy if exists "participants_admin_write" on public.activity_participants;
create policy "participants_admin_write" on public.activity_participants
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- activity_stats (safe to expose)
drop policy if exists "stats_select_public" on public.activity_stats;
create policy "stats_select_public" on public.activity_stats
for select to anon, authenticated
using (true);

-- activities_public view relies only on public tables and safe stats

-- 7) Bootstrap note:
-- To promote a user to admin (run as postgres in SQL editor):
-- update public.profiles set role = 'admin' where email = 'your-admin@email.com';
